### ISSUE TITLE
ActionBar crashes on iOS when first component uses an ActionItem

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#121]
As the title says, if your iOS app’s first component uses an `<ActionItem>` the app crashes.

Code:

```xml
<ActionBar title="Title">
  <ActionItem text="Hi"></ActionItem>
</ActionBar>
```

Error:

```
Mar 18 11:05:47 VANTOLLMAC-7 sampleGroceries[8644]: *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

Mar 18 11:05:47 VANTOLLMAC-7 sampleGroceries[8644]: *** JavaScript call stack:
	(
		0   setLeftBarButtonItemsAnimated@[native code]
		1   populateMenuItems@file:///app/tns_modules/ui/action-bar/action-bar.js:112:53
		2   update@file:///app/tns_modules/ui/action-bar/action-bar.js:90:31
		3   ngOnInit@file:///app/tns_modules/nativescript-angular/directives/action-bar.js:71:35
		4   detectChangesInRecordsInternal@:20:107
		5   detectChangesInRecords@file:///app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:104:48
...
```

**Comment by vakrilov** [comment]
This is a know issue but unfortunately, we still haven't found a way to handle the exception gracefully (it is native exception).
To avoid the exception we have introduced a special `startPageActionBarHidden` property that you can use in the `nativeScriptBootstrap` method to tell NativeScript to load the first page with action-bar shown:
```
nativeScriptBootstrap(AppComponent, null, { startPageActionBarHidden: false });
```

**Comment by tjvantoll** [comment]
Ok thanks. I’ll use that flag to workaround this for now.

**Comment by tjvantoll** [comment]
After upgrading to 0.0.42 I now get this error when using an `<ActionItem>` on any page, not just the first one. You can recreate the problem by bumping up Groceries’ nativescript-angular dependency to 0.0.42 and logging in. This is a blocker for me upgrading Groceries to the newest version.

```
Apr 21 09:03:35 VANTOLLMAC-7 sampleGroceries[4159]: *** JavaScript call stack:
	(
		0   setRightBarButtonItemsAnimated@[native code]
		1   populateMenuItems@file:///app/tns_modules/ui/action-bar/action-bar.js:113:54
		2   update@file:///app/tns_modules/ui/action-bar/action-bar.js:90:31
		3   viewWillAppear@file:///app/tns_modules/ui/page/page.js:119:34
		4   UIApplicationMain@[native code]
		5   start@file:///app/tns_modules/application/application.js:233:26
		6   @file:///app/tns_modules/nativescript-angular/application.js:65:26
		7   ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:475:38
		8   nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:64:23
		9   anonymous@file:///app/main.js:6:36
		10  evaluate@[native code]
		11  moduleEvaluation@:1:11
		12  @:8:48
		13  promiseReactionJob@:1:11
	)
Apr 21 09:03:35 VANTOLLMAC-7 sampleGroceries[4159]: *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x038f8494 __exceptionPreprocess + 180
		1   libobjc.A.dylib                     0x033b2e02 objc_exception_throw + 50
		2   CoreFoundation                      0x037bdaa3 -[__NSArrayM objectAtIndex:] + 243
		3   CoreFoundation                      0x038353b8 -[NSArray objectAtIndexedSubscript:] + 40
		4   UIKit                               0x016c74a3 -[UINavigationBar _setLeftViews:rightViews:] + 5995
		5   UIKit                               0x016add63 -[UINavigationItem updateNavigationBarButtonsAnimated:] + 286
		6   UIKit                               0x016ae9c7 -[UINavigationItem setObject:forLeftRightKeyPath:animated:] + 804
		7   UIKit                               0x016af8e6 -[UINavigationItem setRightBarButtonItems:animated:] + 114
		8   sampleGroceries                     0x007e94e8 ffi_call_i386 + 24

**Comment by vakrilov** [comment]
@tjvantoll #193 should fix this crash. 
Looks like using `ngOnInit` to update the ActionBar causes updates to the navigation bar after the navigation has already started which triggers the exception.

**Comment by nraboy** [comment]
I noticed this was merged today.  I am still getting the error, so I assume it hasn't been tagged yet.  Correct?

**Comment by tjvantoll** [comment]
@nraboy This was included in 0.0.44. When I upgraded this Groceries this error was indeed fixed for me, but I was having an unrelated issue related to the nativescript-restart-on-sync plugin when running `livesync`, so I’m personally staying on 0.0.38 for now.

**Comment by vakrilov** [comment]
@nraboy 
The fix included 0.0.44 fixes a crash [when navigating to the second page](https://github.com/NativeScript/nativescript-angular/issues/121#issuecomment-212912500). The original exception reported in the issues is still there but can be worked around by setting `startPageActionBarHidden: false` in the `nativeScriptBootstrap`.

**Comment by tzraikov** [comment]
The issue seems to be resolved in 0.1.3

**Comment by vchimev** [comment]
This crash is still reproducible at my end with version 0.1.3.

**Comment by patuku-roy** [comment]
And this is affected also when we are not using angular, any solution to avoid this? I'm using NS 2.0.1 ...

**Comment by patuku-roy** [comment]
Maybe I jump to wrong issue, but I'm developing without angular and is happened on my side. I've tried  to looked at Nativescript issues but no luck, nobody mention this problem except this issue. I'm using NS 2.0.1, tns-core-modules 2.0.1, ios-runtime 2.0.1, XCode 7.3.1 ... anyone here has the same problem? and how to fix it?

**Comment by tzraikov** [comment]
@patuku-roy We were not able to reproduce this issue outside of NativeScript Angular. Please, could you give us a link to your app so we can test it and locate the problem. Thank you!

**Comment by patuku-roy** [comment]
@tzraikov is solved now, I put the intermediate page before navigated to the first page which contain the ActionBar and use some delay (500ms) before the app navigated to the page which contain the ActionBar. Maybe this is related to ios loading process ...

**Comment by tzraikov** [comment]
@patuku-roy Actually we located the issue. It appears when using iOS 9.3. The issue will be addressed in our next release.

**Comment by patuku-roy** [comment]
@tzraikov thanks for the reference and your commit, maybe for temporary solution for anyone who has the same problem with me, you can use delay before navigated to the first page using ActionBar. At least until the next version.
