### ISSUE TITLE
Angular 9: Using ngIf changes order of children inside a StackLayout

### ISSUE THREAD

**Issue by OliverNiebsch** [NativeScript/nativescript-angular#2176]
**Environment**
 - CLI: 6.7.4
 - Cross-platform modules: 6.5.0
 - Android Runtime: 6.5.1
 - iOS Runtime: 6.5.1
 - NativeScript-Angular: 9.0.0
 - Angular: 9.1.0
 
**Describe the bug**
After upgrading from Angular 8 to Angular 9: When using `*ngIf` on a component that's together with other components wrapped by a `StackLayout`, the component with ngIf is always added as the last child when the Page is rendered.

```
<StackLayout>
    <Label text="Line 1"></Label>
    <Label text="Line 2" *ngIf="true"></Label>
    <Label text="Line 3"></Label>
</StackLayout>
```

![Screenshot](https://user-images.githubusercontent.com/7679983/84143456-eab71d80-aa56-11ea-85d4-85938473f2b1.jpg)

**To Reproduce**
Just start the app from the sample repository.

**Expected behavior**
"Line 2" is between "Line 1" and "Line 3". ngIf does not change the order of the elements.

**Sample project**
[See here](https://github.com/OliverNiebsch/NativeScriptAngular9)

Please ask when something is left uncleared. Thanks in advance!

**Comment by chevallard** [comment]
Just to add in case it helps: this is occuring in FlexboxLayout as well as the StackLayout mentioned above. An `*ngIf` directive on either an ng-container or directly on an element causes it to always come after elements that don't have the directive, even if the initial value of the `*ngIf` is `true`

I tried manually triggering change detection using ChangeDetectorRef after all elements were loaded, with no luck.

**Comment by sublime392** [comment]
As a work around, I have added an `*ngIf` with a variable that is always true to all the elements that did not already have an `*ngIf`. It seems to be working. The two components I have tried so far are in the correct order after doing this.

**Comment by crowmagnumb** [comment]
This one is biting me in so many ways now. :) Hoping there is a fix real soon for this. :)

**Comment by OliverNiebsch** [comment]
Are there any news on this?

**Comment by iamabs2001** [comment]
> Are there any news on this? Really looking forward to this since it's messing up my UI and I don't like the workaround at all :/

in Progress...

**Comment by pekevski** [comment]
I see this occur with an *ngFor

```
<Label *ngFor="...">
<Label text="BBB">
```

The BBB label will appear before the ngFor labels.

**Comment by ivanthz** [comment]
For now I'm using an additional Stack to get around the problem:

```
<StackLayout>
    <Label text="Line 1"></Label>

    // TODO: Remove additional Stack: *ngIf order error
    <StackLayout>
        <Label text="Line 2" *ngIf="true"></Label>
    </StackLayout>

    <Label text="Line 3"></Label>
</StackLayout>

```

**Comment by crowmagnumb** [comment]
I have not seen this in the nativescript 7 release. I believe this has been fixed.

**Comment by iamabs2001** [comment]
Now All fine with angular 10

**Comment by ivanthz** [comment]
> Now All fine with angular 10

Can you share your package.json?
I'm using NS 7 with Angular 10 and the problem still here.

**Comment by crowmagnumb** [comment]
Did you follow this [upgrade process](https://nativescript.org/blog/nativescript-7-announcement)? I had some issues with it but have them ironed out now.

You should have the latest nativescript globally installed ...

```
npm i -g nativescript@~7.0.0
```

The relevant parts of my `package.json` are ...

```
    "dependencies": {
        ....
        "@nativescript/angular": "^10.0.0",
        "@nativescript/core": "^7.0.0",
        ...
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.1000.3",
        "@angular/cli": "^10.0.0",
        "@angular/compiler-cli": "^10.0.0",
        "@angular/language-service": "^10.0.0",
        "@nativescript/android": "7.0.0",
        "@nativescript/ios": "7.0.0",
        "@nativescript/webpack": "~3.0.3",
        "typescript": "~3.9.0"
    }
```
