### ISSUE TITLE
Dark theme not applied properly when angular template used

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-angular#634]
app.css file content:
`@import 'nativescript-theme-core/css/core.dark.css';`

[Result](https://www.screencast.com/t/zNjS1PIWq)

**Comment by NathanWalker** [comment]
@pkoleva try adding this right after the import line:
Page {
  background-color:#303030;
}

Also do you have a sample of your view setup?

**Comment by NickIliev** [comment]
Closing as resolved with latest versions of tns-core-mdolues and nativescript-theme-core

**Comment by Vetm** [comment]
This problem still occurs when using sass with `@import '~nativescript-theme-core/scss/dark';`
