### ISSUE TITLE
[4.2] Nested Router outlet stops working after page navigation

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-angular#949]
Nested `<router-outlet>` stops working after page navigation.
The problem occurs when you have `<router-outlet>` nested inside a `<page-router-outlet>`. When you navigate to another page and then back again, the nested `<router-outlet>` remains empty and you can no longer navigate in it.

Repro:

1.  Run [this sample](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/app.ts#L43) from the [ng-sample app](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/)
2. Click "Start" -> navigates to second page with nested outlet (green background)
3. Click "Nav to First" -> forward navigation the first page
4. Click back -> we are back to the previous page, but the nested outlet (with the green background) is gone 

Issue reproducible for both Android and IOS.

**Comment by jogboms** [comment]
Mentioned this issue already and even created a sample to prove it too #941

**Comment by davidjonz2005** [comment]
i have the same problem,
i have a tabview with three tab and each of them is a router-outlet when i go to another page and back again all of them disapeared

**Comment by davidjonz2005** [comment]
i think as a workaround we can use "ngIf" instead of "router-outlet" statement. any better suggesion?

**Comment by blueberrynotblue** [comment]
@vakrilov did this solved in 4.4?

**Comment by vakrilov** [comment]
I'm working on it.
The fix for this bug is actually in the `tns-core-modules` as soon as it is fixed you will be able to use it even with `nativescript-angular@4.2`.

**Comment by vakrilov** [comment]
Just deleted my last comment - it was intended for another issue.

This issue is fixed and already in `@next`. It will be also included in the `4.4.0` release

**Comment by jevenson** [comment]
@vakrilov Did this get pushed with 4.4.0? I'm not seeing it listed in the [changelog](https://github.com/NativeScript/nativescript-angular/blob/master/CHANGELOG.md)

**Comment by hackerunet** [comment]
Sorry but this was not included in any other version, in fact the version 4.4 has not been released yet and @next leades me to version 5.0 which I tested and the problem persist.

**Comment by gonick** [comment]
Any resolution to this problem?
After opening a route through <page-router-outlet>
<router-outlet> navigations stopes working.
🤔
